### ISSUE TITLE
Two powerful feral ghoul mobs attack player ghouls.

### ISSUE THREAD

**Issue by Sinbest** [nokele/Fortune13#199]
## Round ID:
368

## Reproduction:

Head to ghoultown, enter the building with the NV and combat knife, the glowing one and legendary will attack you even if you are a ghoul.

EDIT: I found more in the wasteland jail.

**Comment by VEN0M5** [comment]
Intended so the ghoul players don't just get a free NV.

PR #178

**Comment by VictorZisthus** [comment]
> Intended so the ghoul players don't just get a free NV.
> 
> PR #178 

Would it nor be better to have the place be defended by a legendary radscorp, cazador, or raider instead? Having feral ghouls attack other ghouls just seems out of place and lore breaking.
