### ISSUE TITLE
Smelling Salts are broken, Legion cannot revive anyone

### ISSUE THREAD

**Issue by Tailiik** [nokele/Fortune13#26]
## Reproduction:Legion smelling salts are supposed to work as a consumable defib basically, currently they do nothing. It's supposed to give the dead player a prompt to re-enter their body and then be revived like a defib does, instead it gives no prompt and immediately says the person doesn't respond. 

Have had to get admins to aheal legion corpses in several rounds because revivable players were made unrevivable, inadvertently putting a massive nerf on the faction.

**Comment by FantasticFwoosh** [comment]
The affected person's ghost actually has to be inside the body to recieve the salts. Sometimes this contradicts the wishes of people who do not want to be revived and instead want to d-chat observe or have logged off as a reasonable alternative cause why this may have happened. 

* It will also fail if the heart or brain is too damaged from organ decomposition/ they suicided for them to be brought back as a legitimate means.

Maybe it could have more conditional text for these outlying issues why the salts wouldnt work. They aren't as feedback comprehensive as the defibs telling you no brain activity or a broken heart.

**Comment by Tailiik** [comment]
I have had smelling salts not work just a couple minutes after a player died, it wasn't due to organ rot and their soul was still present. They had to be ahealed or revived using an admin spawned defib

**Comment by Tailiik** [comment]
Tribal/legion medical update has fixed this. 

[(っ◔◡◔)っ ♥ Aforementioned pr ♥](https://github.com/nokele/Fortune13/pull/131)
