### ISSUE TITLE
Legion Camp Duty spawns outside of NCR base

### ISSUE THREAD

**Issue by Tailiik** [nokele/Fortune13#272]
## Reproduction: Spawn as legion camp duty, cry when you appear 30 seconds from the NCR's front door. 
EDIT: Upon further research it appears they can spawn at any random wastelander matrix point, but this still includes outside the NCR. Camp duty should spawn inside the camp like everyone else who spawns with a Legion medallion.

**Comment by prox1488** [comment]
Solved, will be patched in my next PR.
