### ISSUE TITLE
Make Respawning or accepting a ghost role enable DNR.

### ISSUE THREAD

**Issue by VictorZisthus** [nokele/Fortune13#274]
As of right now, medical staff have no way to identify if a corpse is in a revivable state or not with their HUD's or examines. Triage is a guessing game.

**What should occur:**
Individuals that use the Respawn verb or accept a ghost role of any kind should mark their body as Do Not Resuscitate before the desired action occurs. This will ensure that medical personnel don't waste time during Triage healing what are effectively corpses. suicide should likewise DNR a person upon its completion, or at the very least prompt the new ghost with a popup window for the verb.

This will mark medical HUD's with a red flatline instead of a pulsing blue EKG icon and will allow medical to, at a glance, perform more effective Triage.

Players with a body that are ghosted but have lost connection with the server should produce the red flatline, but not activate the DNR verb. This red flatline should return to the blue EKG icon when the connection is re-established.

**Comment by prox1488** [comment]
Solved, will be patched in my next PR.

**Comment by VictorZisthus** [comment]
> 
> 
> Solved, will be patched in my next PR.

Cheers!
