### ISSUE TITLE
Laser Musket is lacking an icon

### ISSUE THREAD

**Issue by GMR25** [nokele/Fortune13#61]
Round ID: 262

Testmerges: None?

Reproduction:
1) Craft a Laser Musket (I was using an advanced workbench and had a Hunting Rifle held in the right hand)
2) Wonder where the fuck it is before realizing you're holding it
3) Put it on the floor and look closely at this nonsense
![laser musket](https://user-images.githubusercontent.com/8716237/121825175-e4b5d700-cc7e-11eb-82b9-398aa63399e6.png)

Additional note: It appears on your character sprite (at least, in your character's hands - didn't test the back slot for my own sanity). It also has a sprite when examined (either directly, or examining someone holding it).

This is the sprite when alt-clicking a tile it is on:
![Screenshot_1](https://user-images.githubusercontent.com/8716237/121825684-cd2c1d80-cc81-11eb-83e5-0e8989c42004.png)

**Comment by nokele** [comment]
Fixed.
