### ISSUE TITLE
M1911 has no icon

### ISSUE THREAD

**Issue by GMR25** [nokele/Fortune13#93]
Round ID: 281

Testmerges: None?

Reproduction:
1) Spawn a role with an M1911 or find one in the world
2) Behold the lack of an icon

![Screenshot_2](https://user-images.githubusercontent.com/8716237/122238849-78a9bd80-ce8e-11eb-9456-b0e24eadbed5.png)

**Comment by Pebblesthe2nd** [comment]
fix in the PR queue

**Comment by GMR25** [comment]
Cheers.
